(function(){'use strict';const modes=ArcadeModes,reduced=matchMedia('(prefers-reduced-motion: reduce)'),hero=document.getElementById('hero-art');let raf=0;
 function best(mode){try{const raw=localStorage.getItem(mode.storageKey);if(raw===null)return 'New';const value=JSON.parse(raw);if(typeof value==='number')return value>0?'Best · '+Math.floor(value).toLocaleString():'New';if(!value||typeof value!=='object')return 'New';const entries=Object.values(value).filter(e=>e!==null);if(!entries.length)return 'New';const stars=entries.reduce((n,e)=>n+(Number(e.stars)||0),0);if(stars)return '★ '+stars+' stars';const hearts=entries.reduce((n,e)=>n+(Number(e.hearts)||0),0);if(hearts)return '♥ '+hearts+' best hearts';const times=entries.map(e=>typeof e==='number'?e:e.time).filter(t=>Number.isFinite(t)&&t>0);if(times.length){const t=Math.min(...times);return 'Best · '+Math.floor(t/60)+':'+(t%60).toFixed(1).padStart(4,'0');}return 'New';}catch(e){return 'New';}}
 function launch(mode){try{localStorage.setItem('bubuDuduLastMode',mode.id);}catch(e){}}
 for(const type of ['2D','3D']){const section=document.createElement('section');section.className='mode-section';section.setAttribute('aria-labelledby','heading-'+type);section.innerHTML='<div class="section-heading"><h2 id="heading-'+type+'">'+type+' Games</h2><span>'+modes.filter(m=>m.type===type).length+' little adventures</span></div><div class="mode-grid"></div>';const grid=section.lastElementChild;
  for(const mode of modes.filter(m=>m.type===type)){const a=document.createElement('a');a.className='mode-card';a.href=mode.url;a.dataset.mode=mode.id;a.setAttribute('aria-label',mode.name+' · '+mode.description);a.innerHTML='<div class="mode-preview" aria-hidden="true"><canvas width="160" height="100"></canvas><span class="badge">'+mode.type+'</span></div><div class="mode-copy"><h3>'+mode.name+'</h3><p>'+mode.description+'</p><div class="mode-meta"><span>'+mode.controls+'</span><strong>'+best(mode)+'</strong></div></div>';a.addEventListener('click',()=>launch(mode));a.addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();a.click();}});grid.append(a);const ctx=a.querySelector('canvas').getContext('2d');ctx.fillStyle='#f5dfdf';ctx.beginPath();ctx.ellipse(80,77,65,14,0,0,Math.PI*2);ctx.fill();CharacterRenderer.draw(ctx,48,35,'bubu',.5,0,0,true);CharacterRenderer.draw(ctx,111,35,'dudu',.5,0,0,true);ctx.fillStyle='#aa5c7d';ctx.font='22px Trebuchet MS';ctx.textAlign='center';ctx.fillText(mode.icon,80,28);}
  document.getElementById('games').append(section);
 }
 document.getElementById('mode-count').textContent=modes.length+' little ways to play together';
 function lastPlayed(){let id;try{id=localStorage.getItem('bubuDuduLastMode');}catch(e){}const mode=modes.find(m=>m.id===id)||modes[0],play=document.getElementById('hero-play');play.href=mode.url;play.textContent='Play · '+mode.name;play.onclick=()=>launch(mode);play.onkeydown=e=>{if(e.code==='Space'){e.preventDefault();play.click();}};}
 lastPlayed();addEventListener('pageshow',lastPlayed);
 function drawCharacter(ctx,x,y,kind,scale,time){CharacterRenderer.draw(ctx,x,y,kind,scale,time,0,reduced.matches);}
 function draw(now){raf=0;const width=hero.clientWidth,height=hero.clientHeight,dpr=Math.min(3,devicePixelRatio||1);if(hero.width!==Math.round(width*dpr)||hero.height!==Math.round(height*dpr)){hero.width=Math.round(width*dpr);hero.height=Math.round(height*dpr);}const ctx=hero.getContext('2d');ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,width,height);const factor=Math.min(width/520,height/320);ctx.translate((width-520*factor)/2,(height-320*factor)/2);ctx.scale(factor,factor);
  // Generous feet/shadow margins; the old card canvas clipped the body at large scale.
  ctx.fillStyle='#edd9cd';ctx.beginPath();ctx.ellipse(260,286,205,20,0,0,Math.PI*2);ctx.fill();drawCharacter(ctx,146,120,'bubu',2.15,now/1000);drawCharacter(ctx,374,120,'dudu',2.15,now/1000+.4);ctx.fillStyle='#df8da8';ctx.font='48px Trebuchet MS';ctx.textAlign='center';ctx.fillText('♡',260,90);
  if(!reduced.matches&&!document.hidden)raf=requestAnimationFrame(draw);
 }
 function wake(){if(!raf)raf=requestAnimationFrame(draw);}addEventListener('resize',wake);reduced.addEventListener('change',wake);document.addEventListener('visibilitychange',()=>{if(document.hidden){cancelAnimationFrame(raf);raf=0;}else wake();});wake();
})();