/* One namespace; all world distances are CSS-independent garden units. */
(function(S){
 'use strict';
 S.CONFIG=Object.freeze({bubuSpeed:185,duduSpeed:132,radius:13,rescueRange:49,rescueHold:.8,toolHold:.65,trailSpacing:30,maxTrail:3,carryCount:2,followerSpeed:245,lostDistance:240,maxDelta:.04,gridSize:96,puddleSlow:.42,rainSlow:.67,pushSpeed:100,bounceSeconds:2,bounceCooldown:1.5,historyStep:.05,earlyFraction:.75,stormDuration:120,checkpointRange:36,houseRange:66,particleCap:80,particleLife:.8,cameraSpeed:9,viewScale:1,deliveryPoints:100,heartPoints:25,honeyPoints:75});
 S.state={mode:'menu',level:0,time:0,hearts:0,score:0,delivered:0,lost:0,checkpoint:{x:0,y:0},muted:false};
 S.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
 S.best={};try{const b=JSON.parse(localStorage.getItem('sweetRescueBest')||'{}');if(b&&typeof b==='object'&&!Array.isArray(b))S.best=b;}catch(e){}
 S.unlocked=function(i){return i===0||!!(S.best[i-1]&&S.best[i-1].stars);};
 S.audio={context:null,options:{isMuted:false,x:0,y:0},unlock:function(){try{if(!this.context)this.context=new(window.AudioContext||window.webkitAudioContext)();if(this.context.state==='suspended')this.context.resume().catch(()=>{});VoiceManager.setAudioContext(this.context);VoiceManager.unlock();}catch(e){}},play:function(event){try{this.options.isMuted=S.state.muted;this.options.x=S.player.x;this.options.y=S.player.y;VoiceManager.playBabble(S.player.kind,event,this.options);}catch(e){}},stop:function(){try{VoiceManager.stop();}catch(e){}}};
 S.start=function(index){if(!S.levels[index]||!S.unlocked(index))return;S.input.clear();S.loadLevel(index);Object.assign(S.state,{mode:'playing',level:index,time:0,hearts:0,score:0,delivered:0,lost:0});S.state.checkpoint.x=S.level.spawn.x;S.state.checkpoint.y=S.level.spawn.y;S.player.reset(S.level.spawn);S.render.snap();S.ui.hide();S.ui.toast(S.level.hint,7);S.audio.unlock();};
 S.pause=function(){if(S.state.mode==='playing'){S.state.mode='paused';S.input.clear();S.audio.stop();S.ui.pause();}else if(S.state.mode==='paused'){S.state.mode='playing';S.input.clear();S.ui.hide();S.last=performance.now();}};
 S.returnCheckpoint=function(){if(S.state.mode!=='playing')return;S.player.drop();S.player.x=S.state.checkpoint.x;S.player.y=S.state.checkpoint.y;S.player.clearHistory();S.player.cooldown=S.CONFIG.bounceCooldown;S.input.clear();S.ui.toast('Back under the flower arch. Your friends are safe here.');};
 S.complete=function(){if(S.state.mode!=='playing')return;S.state.mode='complete';S.input.clear();const stars=S.state.time>S.level.timer?1:(S.state.time<=S.level.timer*S.CONFIG.earlyFraction&&S.state.lost===0?3:2),old=S.best[S.state.level]||{};S.state.stars=stars;S.best[S.state.level]={stars:Math.max(old.stars||0,stars),time:Math.min(old.time||Infinity,S.state.time),hearts:Math.max(old.hearts||0,S.state.hearts)};try{localStorage.setItem('sweetRescueBest',JSON.stringify(S.best));}catch(e){}S.audio.play('level');S.ui.summary();};
 S.update=function(dt){if(S.state.mode!=='playing')return;S.state.time+=dt;S.updateEntities(dt);S.player.update(dt);S.render.update(dt);S.ui.update(dt);};
 S.boot=function(){S.input.init();S.ui.init();S.loadLevel(0);S.player.reset(S.level.spawn);S.render.init();S.ui.menu();S.last=performance.now();let frameId=0;function frame(now){frameId=0;if(document.hidden)return;const dt=Math.min(Math.max((now-S.last)/1000,0),S.CONFIG.maxDelta);S.last=now;S.update(dt);S.render.draw();frameId=requestAnimationFrame(frame);}document.addEventListener('visibilitychange',()=>{if(document.hidden){if(S.state.mode==='playing')S.pause();S.input.clear();cancelAnimationFrame(frameId);frameId=0;}else{S.last=performance.now();if(!frameId)frameId=requestAnimationFrame(frame);}});frameId=requestAnimationFrame(frame);};
})(window.Rescue=window.Rescue||{});