(function(S){
 'use strict';
 const C=S.CONFIG,historySize=Math.ceil(C.bounceSeconds/C.historyStep)+3;
 const P=S.player={x:0,y:0,kind:'bubu',partner:{x:0,y:0,kind:'dudu'},trail:[],cooldown:0,hop:0,target:null,historyX:new Float32Array(historySize),historyY:new Float32Array(historySize),historyTime:new Float32Array(historySize),historyIndex:0,historyCount:0,historyClock:0};
 P.clearHistory=function(){this.historyIndex=this.historyCount=0;this.historyClock=0;};
 P.reset=function(pos){this.x=pos.x;this.y=pos.y;this.kind='bubu';this.partner.x=pos.x+45;this.partner.y=pos.y;this.partner.kind='dudu';this.trail.length=0;this.cooldown=0;this.hop=0;this.target=null;this.clearHistory();};
 P.swap=function(){if(S.state.mode!=='playing')return;this.partner.x=this.x;this.partner.y=this.y;this.partner.kind=this.kind;this.kind=this.kind==='bubu'?'dudu':'bubu';this.target=null;for(const f of S.friends)f.progress=0;S.render.emit(this.x,this.y,'sparkle');S.audio.unlock();S.audio.play('hug');S.ui.update(0);};
 P.drop=function(){if(this.trail.length)S.state.lost+=this.trail.length;for(let i=0;i<this.trail.length;i++){const f=this.trail[i];f.status='stranded';f.progress=0;f.x=S.state.checkpoint.x+(i-1)*28;f.y=S.state.checkpoint.y+34;f.freed=true;}this.trail.length=0;};
 P.bump=function(){if(this.cooldown>0)return;this.drop();let index=(this.historyIndex-this.historyCount+historySize)%historySize;const oldest=index;for(let i=0;i<this.historyCount;i++){const j=(oldest+i)%historySize;if(S.state.time-this.historyTime[j]>=C.bounceSeconds)index=j;else break;}if(this.historyCount){this.x=this.historyX[index];this.y=this.historyY[index];}else{this.x=S.state.checkpoint.x;this.y=S.state.checkpoint.y;}this.cooldown=C.bounceCooldown;this.clearHistory();S.render.emit(this.x,this.y,'sparkle');S.audio.play('lostHeart');S.ui.toast('Uwaa! A gentle bounce. Friends are waiting at your checkpoint.');};
 P.moveAxis=function(delta,axis,dt){if(!delta)return;let nx=this.x+(axis==='x'?delta:0),ny=this.y+(axis==='y'?delta:0);nx=Math.max(C.radius,Math.min(S.level.size.w-C.radius,nx));ny=Math.max(C.radius,Math.min(S.level.size.h-C.radius,ny));const nearby=S.query(nx,ny,C.radius);for(let i=0;i<nearby.length;i++){const o=nearby[i];if(!S.solid(o,this.kind)||!S.touch(nx,ny,C.radius,o))continue;if(this.kind==='dudu'&&(o.type==='log'||o.type==='crate')){const d=Math.sign(delta)*C.pushSpeed*dt,ox=o.x+(axis==='x'?d:0),oy=o.y+(axis==='y'?d:0);if(S.canPlace(ox,oy,o.w,o.h,o)){o.x=ox;o.y=oy;S.render.emit(this.x,this.y,'dust',1);S.rebuildGrid();}}return;}this.x=nx;this.y=ny;};
 P.interact=function(dt){let nearest=null,dist=C.rescueRange;for(const f of S.friends){if(f.status!=='stranded')continue;const d=Math.hypot(this.x-f.x,this.y-f.y);if(d<dist){dist=d;nearest=f;}}this.target=nearest;for(const f of S.friends)if(f!==nearest)f.progress=0;
  if(nearest){if(!S.input.action){nearest.progress=0;return;}if(this.trail.length>=C.maxTrail){S.ui.toast('Three little friends already! Bring them home first.');return;}if(!nearest.freed&&((nearest.requires==='bush'&&this.kind!=='bubu')||(nearest.requires==='branch'&&this.kind!=='dudu'))){nearest.progress=0;S.ui.toast(nearest.requires==='bush'?'Bubu can gently untangle this bush.':'Dudu can lift this fallen branch.');return;}nearest.progress+=dt;if(nearest.progress>=C.rescueHold){nearest.freed=true;nearest.status='following';nearest.progress=0;this.trail.push(nearest);S.render.emit(nearest.x,nearest.y,'heart');S.audio.play('catch');S.ui.toast(nearest.name+' is coming with you ♡');}return;}
  for(const o of S.obstacles)if(o.type==='rock'&&o.active){if(this.kind==='dudu'&&S.input.action&&S.touch(this.x,this.y,C.rescueRange,o)){o.progress+=dt;if(o.progress>=C.toolHold){o.active=false;S.render.emit(o.x+o.w/2,o.y+o.h/2,'dust');S.audio.play('hug');}}else o.progress=0;}
 };
 P.update=function(dt){S.input.read(dt);this.cooldown=Math.max(0,this.cooldown-dt);let slow=1;this.hop=0;let nearby=S.query(this.x,this.y,C.radius);for(const o of nearby)if(S.touch(this.x,this.y,C.radius,o)){if(o.type==='puddle'){if(this.kind==='dudu')slow=Math.min(slow,C.puddleSlow);else this.hop=1;}if(o.type==='rain')slow=Math.min(slow,C.rainSlow);}const speed=(this.kind==='bubu'?C.bubuSpeed:C.duduSpeed)*slow;this.moveAxis(S.input.x*speed*dt,'x',dt);this.moveAxis(S.input.y*speed*dt,'y',dt);
  nearby=S.query(this.x,this.y,C.radius);for(const o of nearby)if(o.type==='thorn'&&S.touch(this.x,this.y,C.radius,o)){this.bump();break;}
  this.interact(dt);this.historyClock+=dt;if(this.historyClock>=C.historyStep){this.historyClock=0;const i=this.historyIndex;this.historyX[i]=this.x;this.historyY[i]=this.y;this.historyTime[i]=S.state.time;this.historyIndex=(i+1)%historySize;this.historyCount=Math.min(historySize,this.historyCount+1);}
  let tx=this.x,ty=this.y;for(let i=0;i<this.trail.length;i++){const f=this.trail[i];if(this.kind==='dudu'&&i<C.carryCount){f.x=this.x+(i?19:-19);f.y=this.y-18;}else{const dx=tx-f.x,dy=ty-f.y,d=Math.hypot(dx,dy);if(d>C.lostDistance){S.returnCheckpoint();return;}if(d>C.trailSpacing){const step=Math.min(d-C.trailSpacing,C.followerSpeed*dt);f.x+=dx/d*step;f.y+=dy/d*step;}tx=f.x;ty=f.y;}}
  const house=S.level.safeHouse;if(this.trail.length&&Math.hypot(this.x-house.x,this.y-house.y)<C.houseRange){for(const f of this.trail){f.status='delivered';S.state.delivered++;S.state.score+=C.deliveryPoints;}this.trail.length=0;S.audio.play('combo');S.render.emit(house.x,house.y,'heart');if(S.state.delivered===S.friends.length)S.complete();else S.ui.toast('Home safe! Let’s find the others.');}
 };
})(window.Rescue);