(function(S){
 'use strict';
 const C=S.CONFIG,R=S.render={camera:{x:0,y:0},width:0,height:0,dpr:1,time:0,particles:[],count:0};let ctx,canvas,doorGlow;
 function ellipse(x,y,rx,ry,color){ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,Math.PI*2);ctx.fill();}
 function rect(x,y,w,h,color,r){ctx.fillStyle=color;ctx.beginPath();ctx.roundRect(x,y,w,h,r||0);ctx.fill();}
 function text(t,x,y,size,color){ctx.fillStyle=color||'#62474a';ctx.font='bold '+(size||12)+'px Trebuchet MS';ctx.textAlign='center';ctx.fillText(t,x,y);}
 R.clear=function(){this.count=0;this.time=0;};
 R.snap=function(){this.camera.x=Math.max(0,Math.min(S.level.size.w-this.width,S.player.x-this.width/2));this.camera.y=Math.max(0,Math.min(S.level.size.h-this.height,S.player.y-this.height/2));};
 R.init=function(){canvas=document.getElementById('garden');ctx=canvas.getContext('2d');for(let i=0;i<C.particleCap;i++)this.particles.push({x:0,y:0,vx:0,vy:0,life:0,kind:''});doorGlow=ctx.createRadialGradient(0,0,3,0,0,65);doorGlow.addColorStop(0,'#fff0bcaa');doorGlow.addColorStop(1,'#fff0bc00');const resize=()=>{const box=canvas.getBoundingClientRect();this.dpr=Math.min(devicePixelRatio||1,3);this.width=box.width/C.viewScale;this.height=box.height/C.viewScale;canvas.width=Math.round(box.width*this.dpr);canvas.height=Math.round(box.height*this.dpr);this.snap();this.draw();};window.addEventListener('resize',resize);window.addEventListener('orientationchange',resize);resize();};
 R.emit=function(x,y,kind,amount){if(!this.particles.length)return;const n=S.reduced?1:(amount||8);for(let i=0;i<n&&this.count<C.particleCap;i++){const p=this.particles[this.count++];p.x=x;p.y=y;p.vx=(Math.random()-.5)*75;p.vy=-25-Math.random()*55;p.life=C.particleLife;p.kind=kind;}};
 R.update=function(dt){this.time+=dt;const cx=Math.max(0,Math.min(S.level.size.w-this.width,S.player.x-this.width/2)),cy=Math.max(0,Math.min(S.level.size.h-this.height,S.player.y-this.height/2)),f=1-Math.exp(-C.cameraSpeed*dt);this.camera.x+=(cx-this.camera.x)*f;this.camera.y+=(cy-this.camera.y)*f;for(let i=0;i<this.count;i++){const p=this.particles[i];p.life-=dt;p.x+=p.vx*dt;p.y+=p.vy*dt;if(p.life<=0){const temp=this.particles[i];this.particles[i]=this.particles[--this.count];this.particles[this.count]=temp;i--;}}};
 R.friend=function(f){const t=S.reduced?0:this.time,bob=f.status==='following'?Math.sin(t*8+f.phase)*3:Math.sin(t*3+f.phase)*2,x=f.x,y=f.y+bob;ellipse(x,y+12,15,4,'#59755f18');if(f.kind==='bunny'){ellipse(x-7,y-18,5,15,'#fff7eb');ellipse(x+7,y-18,5,15,'#fff7eb');ellipse(x-7,y-18,2,10,'#f1bbc7');ellipse(x+7,y-18,2,10,'#f1bbc7');}else if(f.kind==='kitten'){ctx.fillStyle='#d6b4a0';ctx.beginPath();ctx.moveTo(x-15,y-4);ctx.lineTo(x-12,y-23);ctx.lineTo(x,y-9);ctx.lineTo(x+12,y-23);ctx.lineTo(x+15,y-4);ctx.fill();}ellipse(x,y,17,15,f.kind==='chick'?'#ffe6a0':f.kind==='kitten'?'#dcc1ad':'#fff7eb');ellipse(x-6,y-3,1.8,2,'#62474a');ellipse(x+6,y-3,1.8,2,'#62474a');ellipse(x-10,y+3,4,2.5,'#f1aebb');ellipse(x+10,y+3,4,2.5,'#f1aebb');if(f.kind==='chick'){ctx.fillStyle='#d5a05c';ctx.beginPath();ctx.moveTo(x-3,y+1);ctx.lineTo(x+3,y+1);ctx.lineTo(x,y+5);ctx.fill();}else text('ᴗ',x,y+7,10);if(f.status==='stranded'){if(!f.freed){if(f.requires==='bush'){ellipse(x-15,y+12,13,9,'#94b595');ellipse(x+13,y+12,14,10,'#94b595');text('✿',x+13,y+13,13,'#f3c2d0');}else{rect(x-24,y+7,48,9,'#aa856b',4);text('Dudu',x,y-32,10);}}text(f.name,x,y+32,10);if(f.progress>0){rect(x-22,y-43,44,6,'#fff8ee',3);rect(x-22,y-43,44*Math.min(1,f.progress/C.rescueHold),6,'#e986a5',3);}else if(S.player.target===f)text('E / ♡',x,y-43,11);}};
 function obstacle(o){const x=o.x,y=o.y,w=o.w,h=o.h;if(!o.active)return;switch(o.type){case 'puddle':ellipse(x+w/2,y+h/2,w/2,h/2,'#acd5db');ellipse(x+w/2-10,y+h/2-4,w*.28,h*.22,'#d3eef0');text('≈',x+w/2,y+h/2+5,18,'#6f9da5');break;case 'thorn':for(let a=0;a<w;a+=24){ellipse(x+a+12,y+h/2,17,h/2,'#9baf8a');text('✧',x+a+12,y+h/2+4,16,'#f3c2ce');}break;case 'log':case 'crate':rect(x,y,w,h,'#b79376',9);ctx.strokeStyle='#896d5e';ctx.lineWidth=3;ctx.strokeRect(x+7,y+7,w-14,h-14);text('⇄ Dudu',x+w/2,y+h/2+4,10);break;case 'rock':ellipse(x+w/2,y+h/2,w/2,h/2,'#b6bbc5');text('ϟ',x+w/2,y+h/2+5,30,'#808591');text('E',x+w/2,y-6,11);break;case 'fence':rect(x,y,w,h,'#d9c8ae',4);for(let a=0;a<h;a+=22)rect(x+3,y+a,w-6,3,'#bfa991');break;case 'gap':rect(x,y,w,h,'#efc9d630',4);text('Bubu',x+w/2,y+h/2,10,'#a67790');break;case 'gate':if(!o.open){rect(x,y,w,h,'#a8b5a6',4);for(let a=0;a<h;a+=15)rect(x,y+a,w,3,'#7c957b');text('✿',x+w/2,y+h/2,15);}else{rect(x,y,w,8,'#a8b5a6',4);rect(x,y+h-8,w,8,'#a8b5a6',4);}break;case 'stone':ellipse(x+w/2,y+h/2,w/2,h/2,o.pressed?'#dfbfca':'#c7c0bf');text(o.heavy?'Dudu ↓':'↓',x+w/2,y+h/2+4,11);break;case 'heart':text('♥',x+w/2,y+h/2+8,27,'#e986a5');break;case 'honey':rect(x,y,w,h,'#e5c277',8);rect(x+2,y-4,w-4,7,'#aa8c72',2);text('♡',x+w/2,y+h/2+5,16);break;}}
 function rain(o){ctx.globalAlpha=.38;rect(o.x,o.y,o.w,o.h,'#aab0bd',22);ctx.globalAlpha=.65;ellipse(o.x+o.w*.3,o.y+8,o.w*.27,22,'#e4dbe2');ellipse(o.x+o.w*.6,o.y,o.w*.28,28,'#e4dbe2');ellipse(o.x+o.w*.8,o.y+12,o.w*.2,18,'#e4dbe2');ctx.strokeStyle='#9fabbc';ctx.lineWidth=2;const drift=S.reduced?0:(R.time*22)%24;ctx.beginPath();for(let i=12;i<o.w;i+=23){ctx.moveTo(o.x+i,o.y+35+drift);ctx.lineTo(o.x+i-4,o.y+44+drift);}ctx.stroke();ctx.globalAlpha=1;}
 // The shared renderer's origin is the head centre. Adapt it to a foot anchor.
 R.drawCharacter=function(context,x,y,kind,scale,outline){const style=CharacterRenderer.CHARACTER_STYLE[kind],headY=y-(style.fY+style.fH)*scale;context.save();if(outline)context.globalAlpha=.22;CharacterRenderer.draw(context,x,headY,kind,scale,this.time,0,S.reduced);if(outline){context.strokeStyle=style.outline;context.lineWidth=1.5;context.setLineDash([4,5]);context.beginPath();context.ellipse(x,y-29,24,32,0,0,Math.PI*2);context.stroke();context.setLineDash([]);}context.restore();};
 R.draw=function(){if(!ctx)return;ctx.setTransform(this.dpr*C.viewScale,0,0,this.dpr*C.viewScale,0,0);ctx.clearRect(0,0,this.width,this.height);ctx.fillStyle='#d9e7c5';ctx.fillRect(0,0,this.width,this.height);ctx.save();ctx.translate(-this.camera.x,-this.camera.y);rect(0,0,S.level.size.w,S.level.size.h,'#d9e7c5',18);const x0=Math.floor(this.camera.x/65)*65,y0=Math.floor(this.camera.y/65)*65;for(let y=y0;y<this.camera.y+this.height+65;y+=65)for(let x=x0;x<this.camera.x+this.width+65;x+=65){if(x<0||y<0||x>S.level.size.w||y>S.level.size.h)continue;text((x+y)%130?'✿':'ˇ',x+21,y+18,12,(x+y)%130?'#ecc5c6':'#afc795');}
  const house=S.level.safeHouse;ctx.save();ctx.translate(house.x,house.y);ctx.fillStyle=doorGlow;ctx.fillRect(-70,-70,140,140);rect(-45,-60,90,68,'#fff1dc',12);ctx.fillStyle='#dca7a7';ctx.beginPath();ctx.moveTo(-55,-58);ctx.lineTo(0,-100);ctx.lineTo(55,-58);ctx.closePath();ctx.fill();rect(-14,-33,28,41,'#e8c97f',13);rect(-34,-40,15,16,'#bddde1',4);rect(20,-40,15,16,'#bddde1',4);text('SAFE HOUSE',0,-108,11);text(S.state.delivered+' / '+S.friends.length+' home',0,31,12);ctx.restore();
  for(const o of S.obstacles)if(o.type!=='rain')obstacle(o);for(const cp of S.checkpoints){ctx.strokeStyle=cp.active?'#cb83a1':'#98b994';ctx.lineWidth=5;ctx.beginPath();ctx.arc(cp.x,cp.y,27,Math.PI,Math.PI*2);ctx.stroke();for(let i=0;i<5;i++)text('✿',cp.x+Math.cos(Math.PI+i*Math.PI/4)*27,cp.y+Math.sin(Math.PI+i*Math.PI/4)*27,15,'#e9aec4');text('Checkpoint',cp.x,cp.y+22,10);}
  this.drawCharacter(ctx,S.player.partner.x,S.player.partner.y,S.player.partner.kind,.52,true);for(const f of S.friends)if(f.status!=='delivered'&&!(f.status==='following'&&S.player.kind==='dudu'&&S.player.trail.indexOf(f)<C.carryCount))this.friend(f);
  const hop=S.player.hop&&!S.reduced?Math.abs(Math.sin(this.time*10))*9:0;ctx.globalAlpha=S.player.cooldown>0?.75:1;this.drawCharacter(ctx,S.player.x,S.player.y-hop,S.player.kind,.52,false);ctx.globalAlpha=1;for(let i=0;i<S.player.trail.length&&S.player.kind==='dudu'&&i<C.carryCount;i++)this.friend(S.player.trail[i]);
  for(const o of S.obstacles)if(o.type==='rain'&&o.active)rain(o);for(let i=0;i<this.count;i++){const p=this.particles[i];ctx.globalAlpha=p.life/C.particleLife;text(p.kind==='heart'?'♥':p.kind==='sparkle'?'✧':'·',p.x,p.y,p.kind==='dust'?18:15,p.kind==='dust'?'#ab947d':'#db88a6');}ctx.globalAlpha=1;ctx.restore();
  const fraction=Math.min(1,S.state.time/(S.level.timer||C.stormDuration));ctx.fillStyle='rgba(136,115,143,'+(fraction*.2)+')';ctx.fillRect(0,0,this.width*fraction,this.height);if(fraction>.6){ctx.globalAlpha=(fraction-.6)*.6;ellipse(this.width*.8,this.height*.03,this.width*.25,30,'#aaa2b4');ellipse(this.width*.45,-10,this.width*.3,40,'#bcb0c0');ctx.globalAlpha=1;}
 };
})(window.Rescue);