(function(S){
 'use strict';
 const U=S.ui={toastTime:0,hudTime:0};let panel,overlay,toast,portrait,portraitCtx,delivered,hearts,timer,storm,levelName,characterName;
 function button(label,fn,primary){const b=document.createElement('button');b.textContent=label;if(primary)b.className='primary';b.onclick=fn;panel.appendChild(b);return b;}
 function card(title,description){S.input.clear();overlay.hidden=false;panel.innerHTML='';const h=document.createElement('h2');h.textContent=title;panel.appendChild(h);if(description){const p=document.createElement('p');p.textContent=description;panel.appendChild(p);}S.audio.stop();}
 function focus(){const b=panel.querySelector('button:not(:disabled)');if(b)b.focus({preventScroll:true});}
 U.init=function(){panel=document.getElementById('panel');overlay=document.getElementById('overlay');toast=document.getElementById('toast');portrait=document.getElementById('portrait');portraitCtx=portrait.getContext('2d');delivered=document.getElementById('delivered');hearts=document.getElementById('hearts');timer=document.getElementById('timer');storm=document.getElementById('storm');levelName=document.getElementById('level-name');characterName=document.getElementById('character-name');document.getElementById('pause').onclick=S.pause;document.getElementById('mute').onclick=U.mute;overlay.addEventListener('keydown',e=>{if(e.code!=='Tab')return;const bs=panel.querySelectorAll('button:not(:disabled)'),first=bs[0],last=bs[bs.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}});};
 U.hide=function(){overlay.hidden=true;this.update(0);document.getElementById('garden').focus({preventScroll:true});};
 U.menu=function(){S.state.mode='menu';card('Sweet Rescue','Bubu & Dudu bring little friends home before the gentle rain.');const art=document.createElement('canvas');art.width=340;art.height=196;art.style.width='170px';art.style.height='98px';const c=art.getContext('2d');S.render.drawCharacter(c,100,172,'bubu',1.1,false);S.render.drawCharacter(c,230,172,'dudu',1.1,false);panel.appendChild(art);button('Play ♡',()=>{let index=0;while(index<S.levels.length-1&&S.best[index]&&S.best[index].stars)index++;S.start(index);},true);button('Level Select',()=>U.select());button('How to Play',()=>U.help());focus();};
 U.select=function(){card('Garden paths','Complete each garden to unlock the next. Your best stars, time and hearts stay saved.');const grid=document.createElement('div');grid.className='level-grid';panel.appendChild(grid);S.levels.forEach((level,i)=>{const b=document.createElement('button'),small=document.createElement('small'),best=S.best[i];b.textContent=(i+1)+'. '+level.name;b.disabled=!S.unlocked(i);small.textContent=best?'★'.repeat(best.stars)+' · '+best.time.toFixed(1)+'s · ♡ '+best.hearts:b.disabled?'Complete the previous garden':'Ready for rescue';b.appendChild(small);b.onclick=()=>S.start(i);grid.appendChild(b);});button('Menu',()=>U.menu());focus();};
 U.help=function(){card('A little teamwork','WASD / arrows move. Space swaps. Hold E near a friend or cracked rock; on touch, tap Rescue. R returns to your flower checkpoint. P / Esc pauses, M mutes.');const p=document.createElement('p');p.textContent='Bubu is quick, hops puddles, fits pink fence gaps and frees bush friends. Dudu pushes logs/crates by walking into them, breaks rocks, lifts branches and carries two friends. Up to three follow either buddy. Leave Dudu on a heavy pressure stone and swap to open its gate. Thorns gently bounce you back two seconds; dropped friends wait at your checkpoint. The storm is a soft deadline, not a game over. 3 stars: finish early without dropping friends. 2: finish before rain. 1: finish late.';panel.appendChild(p);button('Menu',()=>U.menu(),true);focus();};
 U.pause=function(){card('A little breather','The garden and the storm are waiting for you.');button('Resume',()=>S.pause(),true);button('Replay',()=>S.start(S.state.level));button('Menu',()=>U.menu());focus();};
 U.summary=function(){card('Everyone is home!','A garden full of little happy hearts.');const stars=document.createElement('div');stars.className='stars';stars.textContent='★'.repeat(S.state.stars)+'☆'.repeat(3-S.state.stars);stars.setAttribute('aria-label',S.state.stars+' of 3 stars');panel.appendChild(stars);const stats=document.createElement('div');stats.className='summary';stats.innerHTML='<div>Time<strong>'+S.state.time.toFixed(1)+'s</strong></div><div>Hearts<strong>'+S.state.hearts+'</strong></div><div>Points<strong>'+S.state.score+'</strong></div>';panel.appendChild(stats);if(S.state.level+1<S.levels.length)button('Next',()=>S.start(S.state.level+1),true);button('Replay',()=>S.start(S.state.level));button('Menu',()=>U.menu());focus();};
 U.toast=function(message,duration){if(toast.textContent===message&&this.toastTime>0)return;toast.textContent=message;toast.hidden=false;this.toastTime=duration||3;};
 U.mute=function(){S.state.muted=!S.state.muted;try{VoiceManager.setMuted(S.state.muted);}catch(e){}const b=document.getElementById('mute');b.textContent=S.state.muted?'♪̸':'♫';b.setAttribute('aria-pressed',String(S.state.muted));b.setAttribute('aria-label',S.state.muted?'Unmute sound':'Mute sound');};
 U.update=function(dt){this.toastTime=Math.max(0,this.toastTime-dt);if(!this.toastTime)toast.hidden=true;this.hudTime-=dt;if(this.hudTime>0&&dt)return;this.hudTime=.1;levelName.textContent=S.level.name;delivered.textContent=S.state.delivered+' / '+S.friends.length+' friends home';hearts.textContent='♡ '+S.state.hearts;const left=Math.max(0,Math.ceil(S.level.timer-S.state.time));timer.textContent=left?Math.floor(left/60)+':'+String(left%60).padStart(2,'0'):'Gentle rain';storm.value=Math.max(0,1-S.state.time/S.level.timer);characterName.textContent=(S.player.kind==='bubu'?'Bubu':'Dudu')+' · ⇄ Space';portraitCtx.clearRect(0,0,44,44);S.render.drawCharacter(portraitCtx,22,42,S.player.kind,.38,false);document.getElementById('pause').setAttribute('aria-label',S.state.mode==='paused'?'Resume game':'Pause game');};
})(window.Rescue);