'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
async function main(){const pages=await(await fetch('http://localhost:9222/json/list')).json(),page=pages.find(p=>p.type==='page');assert(page);const ws=new WebSocket(page.webSocketDebuggerUrl);await new Promise(r=>ws.addEventListener('open',r));let id=0;const pending=new Map(),errors=[];ws.addEventListener('message',e=>{const m=JSON.parse(e.data);if(m.id){const p=pending.get(m.id);pending.delete(m.id);m.error?p.reject(Error(m.error.message)):p.resolve(m.result);}if(m.method==='Runtime.exceptionThrown')errors.push(JSON.stringify(m.params.exceptionDetails));});const send=(method,params={})=>new Promise((resolve,reject)=>{const n=++id;pending.set(n,{resolve,reject});ws.send(JSON.stringify({id:n,method,params}));}),wait=ms=>new Promise(r=>setTimeout(r,ms));async function evaluate(expression){const r=await send('Runtime.evaluate',{expression,returnByValue:true,awaitPromise:true});if(r.exceptionDetails)throw Error(JSON.stringify(r.exceptionDetails));return r.result.value;}const root='file:///'+path.resolve(__dirname,'..').replace(/\\/g,'/')+'/';async function go(file){await send('Page.navigate',{url:root+file});await wait(1000);}try{
 await send('Runtime.enable');await send('Page.enable');await go('index.html');const modes=await evaluate('ArcadeModes');assert.equal(modes.length,7);assert(await evaluate('!document.getElementById("game")&&!document.getElementById("hud")&&document.querySelectorAll(".mode-card").length===ArcadeModes.length'));console.log('PASS dedicated hub, catalog-driven counts and cards');
 await evaluate('ArcadeSettings.set({muted:true,voices:false,volume:.2});localStorage.setItem("loveCatchBest","1234");localStorage.setItem("cozyKartBest",JSON.stringify({garden:82.5}));localStorage.setItem("sweetRescueBest",JSON.stringify({0:{stars:3}}))');await go('index.html');assert(await evaluate('document.querySelector("[data-mode=catch]").textContent.includes("1,234")&&document.querySelector("[data-mode=kart]").textContent.includes("1:22.5")&&document.querySelector("[data-mode=rescue]").textContent.includes("3 stars")'));console.log('PASS legacy best-score / stars / race-time formats');
 for(const width of [360,768,1280,800]){const height=width===800?360:900;await send('Emulation.setDeviceMetricsOverride',{width,height,deviceScaleFactor:3,mobile:width<801});await wait(150);const layout=await evaluate(`({scroll:document.documentElement.scrollWidth,columns:getComputedStyle(document.querySelector('.mode-grid')).gridTemplateColumns.split(' ').length,art:document.getElementById('hero-art').getBoundingClientRect().height,dpr:document.getElementById('hero-art').width/document.getElementById('hero-art').clientWidth,bad:Array.from(document.querySelectorAll('a,button,input')).filter(e=>{const r=e.getBoundingClientRect();return r.width&&r.height&&(r.height<44||r.width<44)}).map(e=>e.outerHTML)})`);assert(layout.scroll<=width,JSON.stringify(layout));assert.equal(layout.columns,width<601?1:width<951?2:3);assert(layout.dpr<=3.01);assert.equal(layout.bad.length,0,JSON.stringify(layout.bad));console.log('PASS hub layout '+width+'×'+height);}
 for(const m of modes){await go('index.html');await evaluate(`localStorage.removeItem('bubuDuduHelp_${m.id}');document.querySelector('[data-mode="${m.id}"]').click()`);await wait(1100);assert(await evaluate(`location.href.includes(${JSON.stringify(m.url)})`),m.name+' destination');assert(await evaluate('!!document.querySelector(".product-nav a")'),'back link');assert(await evaluate('ArcadeSettings.state.muted&&!VoiceManager.isOn()&&ArcadeSettings.state.volume===.2'),m.name+' settings');assert(await evaluate('!!document.querySelector(".product-modal:not([hidden])")'),m.name+' onboarding');await evaluate('document.querySelector(".product-modal:not([hidden]) button").click()');await wait(150);if(m.type==='2D'&&['catch','picnic','runner'].includes(m.id))assert(await evaluate('ArcadeGame.state.mode==="playing"'),'2D direct start');
  for(const width of [360,768,1280,800]){await send('Emulation.setDeviceMetricsOverride',{width,height:width===800?360:900,deviceScaleFactor:1,mobile:width<801});await wait(120);const l=await evaluate(`({scroll:document.documentElement.scrollWidth,bar:document.querySelector('.product-chrome').getBoundingClientRect().bottom,top:parseFloat(getComputedStyle(document.body).paddingTop),bad:Array.from(document.querySelectorAll('button,a,input,summary')).filter(e=>{const r=e.getBoundingClientRect(),s=getComputedStyle(e);return r.width&&r.height&&s.visibility!=='hidden'&&!e.closest('[hidden],.hidden,.product-native-paused')&&(r.height<43.9||r.width<43.9)}).map(e=>e.id||e.textContent.trim().slice(0,30))})`);assert(l.scroll<=width,m.name+' overflow '+width+' '+JSON.stringify(l));assert(l.bar<=l.top+1,m.name+' chrome overlap '+JSON.stringify(l));assert.equal(l.bad.length,0,m.name+' targets '+JSON.stringify(l));}
  await evaluate('document.querySelector(".product-nav a").click()');await wait(700);assert(await evaluate(`document.getElementById('hero-play').getAttribute('href')===${JSON.stringify(m.url)}`));console.log('PASS '+m.name+' launch, onboarding, audio, Back to Hub, last-played and four layouts');
 }
 await go('arcade.html?mode=catch');await evaluate('ArcadeGame.pause()');await wait(180);assert(await evaluate('!document.querySelectorAll(".product-modal")[1].hidden'));await evaluate('document.querySelectorAll(".product-modal")[1].querySelector("button").click()');assert(await evaluate('ArcadeGame.state.mode==="playing"'));console.log('PASS shared pause / resume');
 await go('index.html');await send('Emulation.setDeviceMetricsOverride',{width:1280,height:900,deviceScaleFactor:1,mobile:false});await evaluate('document.querySelector("[data-mode=catch]").focus()');await send('Input.dispatchKeyEvent',{type:'keyDown',key:' ',code:'Space'});await send('Input.dispatchKeyEvent',{type:'keyUp',key:' ',code:'Space'});await wait(800);assert(await evaluate('location.pathname.endsWith("arcade.html")'));console.log('PASS Space keyboard launch');
 await go('index.html');const shot=await send('Page.captureScreenshot',{format:'png'});fs.mkdirSync(path.join(__dirname,'..','test-results'),{recursive:true});fs.writeFileSync(path.join(__dirname,'..','test-results','hub-desktop.png'),Buffer.from(shot.data,'base64'));assert.equal(errors.length,0,errors.join('\n'));console.log('PASS no runtime exceptions');
 }finally{ws.close();}}
main().catch(e=>{console.error(e);process.exitCode=1;});