(function(S){'use strict';
 const box=new THREE.BoxGeometry(1,1,1),ball=new THREE.SphereGeometry(1,12,8),cylinder=new THREE.CylinderGeometry(1,1,1,16),ring=new THREE.TorusGeometry(1,.09,6,24),heartShape=new THREE.Shape();heartShape.moveTo(0,-.5);heartShape.bezierCurveTo(-1,.1,-.6,.8,0,.35);heartShape.bezierCurveTo(.6,.8,1,.1,0,-.5);const heart=new THREE.ExtrudeGeometry(heartShape,{depth:.12,bevelEnabled:false});
 function mesh(g,color,pos,scale,parent){const m=new THREE.Mesh(g,S.material(color));m.position.set(...pos);m.scale.set(...scale);m.castShadow=true;m.receiveShadow=true;parent.add(m);return m;}
 S.sparkles=[];
 S.sparkle=function(pos){if(S.reduced)return;for(let i=0;i<8;i++){const m=mesh(ball,'#ffe7b0',[pos.x,pos.y+1,pos.z],[.06,.06,.06],S.world);S.sparkles.push({mesh:m,life:.6,dx:(Math.random()-.5)*2,dz:(Math.random()-.5)*2});}};
 S.loadLevel=function(index){if(S.world)S.scene.remove(S.world);S.world=new THREE.Group();S.scene.add(S.world);S.level=S.levels[index];S.entities=[];S.sparkles=[];
  const defs=S.level.entities.concat(S.level.checkpoints.map(c=>({id:c.id,type:'checkpoint',position:c.position,size:[2,2,2],properties:{}})),[{id:'goal',type:'goal',position:S.level.goal.position,size:[2,2,2],properties:{}}]);
  defs.forEach(def=>{const e={...def,props:def.properties||{},pos:new THREE.Vector3(...def.position),size:new THREE.Vector3(...def.size),home:new THREE.Vector3(...def.position),delta:new THREE.Vector3(),active:true,solid:['platform','moving','crumble','gate','crate','cracked','lift'].includes(def.type),timer:0,pressed:false,triggered:false};const group=new THREE.Group();group.position.copy(e.pos);S.world.add(group);e.mesh=group;
   const color={platform:'#bee0c6',moving:'#b8dce9',crumble:'#efd3af',gate:'#c6b4d9',crate:'#c99a72',cracked:'#e7b9cd',lift:'#b8dce9'}[e.type];
   if(e.solid){mesh(e.props.rounded?cylinder:box,color,[0,0,0],e.props.rounded?[e.size.x/2,e.size.y,e.size.z/2]:e.size.toArray(),group);if(e.type==='platform')mesh(box,'#e1efd2',[0,e.size.y/2+.015,0],[e.size.x*.93,.05,e.size.z*.93],group);if(e.type==='crate'){for(const a of [-1,1])mesh(box,'#f0d7af',[a*.42,0,.66],[.12,1.25,.025],group);}if(e.type==='cracked'){for(const a of [-1,1]){const crack=mesh(box,'#b47c99',[a*.3,.51,0],[.045,.025,3],group);crack.rotation.y=a*.4;}}}
   else if(e.type==='plate'){mesh(box,e.props.heavy?'#e3bc6c':'#87c5b2',[0,0,0],e.size.toArray(),group);mesh(box,'#fff0d3',[0,.09,0],[.5,.025,.5],group);}
   else if(e.type==='bounce'){mesh(cylinder,'#fff0d6',[0,-.1,0],[.22,.5,.22],group);mesh(ball,'#e897b4',[0,.18,0],[.9,.28,.9],group);for(let i=0;i<5;i++)mesh(ball,'#fff4e2',[Math.sin(i*2)*.5,.39,Math.cos(i*2)*.5],[.08,.035,.08],group);}
   else if(e.type==='heart'){mesh(heart,'#ee89ad',[0,0,0],[.43,.43,.43],group);}
   else if(e.type==='honey'){mesh(cylinder,'#e6b863',[0,0,0],[.23,.38,.23],group);mesh(cylinder,'#fff0ce',[0,.23,0],[.25,.1,.25],group);mesh(box,'#fff1db',[0,0,.231],[.24,.18,.025],group);}
   else if(e.type==='checkpoint'){const arch=mesh(ring,'#b0d6b8',[0,1,0],[1,1.2,1],group);for(let i=0;i<7;i++)mesh(ball,i%2?'#edafc8':'#fff0be',[Math.cos(i*Math.PI/6),1+Math.sin(i*Math.PI/6)*1.2,.05],[.16,.16,.1],group);arch.castShadow=false;}
   else if(e.type==='goal'){mesh(cylinder,'#fff4dc',[0,1.2,0],[.06,2.4,.06],group);mesh(heart,'#ed82a6',[.48,2,0],[.8,.8,.8],group);}
   S.entities.push(e);
  });
  S.decor=[];for(let i=0;i<18;i++){const cloud=new THREE.Group();cloud.position.set(Math.sin(i*2.3)*24,-3+(i%4)*3,i*4-12);for(let j=0;j<3;j++)mesh(ball,'#fff8f3',[j*1.2,0,0],[1.6, .6,1],cloud);S.world.add(cloud);S.decor.push(cloud);}for(let i=0;i<8;i++){const island=mesh(cylinder,'#d7dbe6',[i%2?-20:20,-4,i*8],[3,.8,2],S.world);S.decor.push(island);}S.petals=[];if(!S.reduced)for(let i=0;i<16;i++){const petal=mesh(ball,'#f5c7da',[(i%5-2)*7,4+i%4,i*4],[.08,.03,.14],S.world);S.petals.push(petal);}
 };
 S.updateEntities=function(dt){const p=S.player;
  S.entities.forEach(e=>{const old=e.pos.clone();e.delta.set(0,0,0);
   if(e.type==='moving'){e.timer+=dt;const path=e.props.path||[3,0,0];if(e.props.circular){e.pos.x=e.home.x+Math.cos(e.timer*(e.props.speed||1))*path[0];e.pos.z=e.home.z+Math.sin(e.timer*(e.props.speed||1))*path[2];}else e.pos.copy(e.home).add(new THREE.Vector3(...path).multiplyScalar(Math.sin(e.timer*(e.props.speed||1))));}
   if(e.type==='crumble'&&e.triggered){e.timer+=dt;const delay=e.delay||1;if(e.timer>delay){e.active=false;e.pos.y-=dt*7;}if(e.timer>delay+4){e.pos.copy(e.home);e.active=true;e.triggered=false;e.timer=0;}}
   if(e.type==='plate'){const atop=actor=>Math.abs(actor.pos.x-e.pos.x)<e.size.x/2+.2&&Math.abs(actor.pos.z-e.pos.z)<e.size.z/2+.2&&Math.abs(actor.pos.y-(e.pos.y+e.size.y/2))<.3;const pressed=(p.grounded&&atop(p)&&(!e.props.heavy||p.kind==='dudu'))||S.entities.some(c=>c.type==='crate'&&atop({pos:new THREE.Vector3(c.pos.x,c.pos.y-c.size.y/2,c.pos.z)}));if(pressed&&!e.pressed){S.audio.play('plate');S.ui.toast(e.props.heavy?'Heavy plate pressed! Leave the crate here.':'The garden gate is open ♡');}e.pressed=pressed;e.triggered=e.props.latch?(e.triggered||pressed):pressed;}
   e.delta.copy(e.pos).sub(old);
  });
  S.entities.forEach(e=>{if(e.type==='gate'||e.type==='lift'){const plates=S.entities.filter(p=>p.type==='plate'&&(p.props.targets||[]).includes(e.id)),open=plates.some(p=>p.triggered);if(open&&!e.open)S.audio.play('gate');e.open=open;const old=e.pos.y,target=e.type==='gate'?e.home.y+(open?e.size.y+1:0):(open?e.props.raisedY:e.home.y);e.pos.y+=Math.max(-dt*4,Math.min(dt*4,target-e.pos.y));e.delta.y=e.pos.y-old;}
   if(e.type==='crate'){const bottom=e.pos.y-e.size.y/2;let top=-Infinity;for(const support of S.entities){if(support===e||!support.solid||!support.active||support.type==='gate')continue;if(Math.abs(e.pos.x-support.pos.x)<(e.size.x+support.size.x)/2&&Math.abs(e.pos.z-support.pos.z)<(e.size.z+support.size.z)/2){const t=support.pos.y+support.size.y/2;if(t<=bottom+.08)top=Math.max(top,t);}}if(bottom>top+.01){e.vy=(e.vy||0)-S.CONFIG.gravity*dt;e.pos.y=Math.max(top+e.size.y/2,e.pos.y+e.vy*dt);}else e.vy=0;if(e.pos.y<S.CONFIG.fallZone)e.pos.copy(e.home);}
   e.mesh.position.copy(e.pos);e.mesh.visible=e.active;
  });
 };
 S.animateEntities=function(dt){const time=S.visualTime||0;S.entities.forEach(e=>{if(e.type==='heart'||e.type==='honey'){e.mesh.rotation.y=time*.8;e.mesh.position.y=e.pos.y+Math.sin(time*2+e.pos.z)*.12;}if(e.type==='crumble'&&e.triggered&&e.active&&!S.reduced)e.mesh.position.x=e.pos.x+Math.sin(time*55)*.035;});S.decor.forEach((d,i)=>{if(!S.reduced)d.position.y+=Math.cos(time*.7+i)*dt*.05;});S.petals.forEach((p,i)=>{p.position.x+=Math.sin(time+i)*dt*.16;p.position.y-=dt*.1;if(p.position.y<-3)p.position.y=8;});S.sparkles=S.sparkles.filter(p=>{p.life-=dt;p.mesh.position.x+=p.dx*dt;p.mesh.position.z+=p.dz*dt;p.mesh.position.y+=dt;const s=Math.max(0,p.life)*.1;p.mesh.scale.setScalar(s);if(p.life<=0){S.world.remove(p.mesh);return false;}return true;});};
})(window.SkyHop);