(function(S){'use strict';const keys=new Set(),held=new Set();let joy={x:0,y:0},orbit=null,joystickId=null;S.input={jump:false,jumpHeld:false,pound:false,
 clear(){keys.clear();held.clear();joy={x:0,y:0};this.jump=this.jumpHeld=this.pound=false;orbit=null;joystickId=null;const stick=document.getElementById('stick');if(stick)stick.style.transform='';},
 axes(){let x=joy.x+(keys.has('d')||keys.has('arrowright')?1:0)-(keys.has('a')||keys.has('arrowleft')?1:0),y=joy.y+(keys.has('s')||keys.has('arrowdown')?1:0)-(keys.has('w')||keys.has('arrowup')?1:0);const n=Math.max(1,Math.hypot(x,y));return{x:x/n,y:y/n};},
 down(){return keys.has('s')||keys.has('arrowdown')||this.pound;},
 init(){
  window.addEventListener('keydown',e=>{if(e.target.matches('input'))return;const k=e.key.toLowerCase();if([' ','tab','arrowup','arrowdown','arrowleft','arrowright'].includes(k))e.preventDefault();S.audio.unlock();keys.add(k);if(e.repeat)return;if(k===' '){this.jump=true;this.jumpHeld=true;}if(k==='q'||k==='tab')S.player.swap();if(k==='r')S.respawn();if(k==='p'||k==='escape')S.pause();if(k==='m')S.audio.toggle();});
  window.addEventListener('keyup',e=>{keys.delete(e.key.toLowerCase());if(e.key===' ')this.jumpHeld=held.size>0;});window.addEventListener('blur',()=>{this.clear();if(S.state.mode==='playing')S.pause();});
  window.addEventListener('pointerdown',()=>S.audio.unlock(),{passive:true});
  const canvas=document.getElementById('world');canvas.addEventListener('pointerdown',e=>{canvas.setPointerCapture(e.pointerId);orbit={id:e.pointerId,x:e.clientX,y:e.clientY};});canvas.addEventListener('pointermove',e=>{if(!orbit||orbit.id!==e.pointerId)return;S.cameraYaw-=(e.clientX-orbit.x)*.006;S.cameraPitch=Math.max(.12,Math.min(1.12,S.cameraPitch+(e.clientY-orbit.y)*.004));orbit.x=e.clientX;orbit.y=e.clientY;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])canvas.addEventListener(ev,()=>{orbit=null;});
  const pad=document.getElementById('joystick'),stick=document.getElementById('stick');const move=e=>{const r=pad.getBoundingClientRect(),x=e.clientX-r.left-r.width/2,y=e.clientY-r.top-r.height/2,n=Math.max(1,Math.hypot(x,y)/36);joy={x:x/n/36,y:y/n/36};stick.style.transform=`translate(${x/n}px,${y/n}px)`;};pad.addEventListener('pointerdown',e=>{if(joystickId!==null)return;joystickId=e.pointerId;pad.setPointerCapture(e.pointerId);move(e);});pad.addEventListener('pointermove',e=>{if(e.pointerId===joystickId)move(e);});for(const ev of ['pointerup','pointercancel','lostpointercapture'])pad.addEventListener(ev,e=>{if(e.pointerId===joystickId){joystickId=null;joy={x:0,y:0};stick.style.transform='';}});
  const jump=document.getElementById('touch-jump');jump.addEventListener('pointerdown',e=>{jump.setPointerCapture(e.pointerId);held.add(e.pointerId);this.jump=true;this.jumpHeld=true;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])jump.addEventListener(ev,e=>{held.delete(e.pointerId);this.jumpHeld=held.size>0||keys.has(' ');});
  document.getElementById('touch-swap').onclick=()=>S.player.swap();const pound=document.getElementById('touch-pound');pound.addEventListener('pointerdown',e=>{pound.setPointerCapture(e.pointerId);this.pound=true;this.jump=true;});for(const ev of ['pointerup','pointercancel','lostpointercapture'])pound.addEventListener(ev,()=>{this.pound=false;});
 }
};})(window.SkyHop);