(function(S){'use strict';const $=id=>document.getElementById(id);let toastTime=0;const time=t=>Math.floor(t/60)+':'+String(Math.floor(t%60)).padStart(2,'0');
 S.ui={
 init(){$('pause').onclick=()=>S.pause();$('character').onclick=()=>S.player.swap();$('mute').onclick=()=>S.audio.toggle();$('volume').oninput=e=>S.audio.setVolume(Number(e.target.value));$('panel').addEventListener('click',e=>{const b=e.target.closest('[data-action]');if(!b)return;const action=b.dataset.action;if(action==='play')S.start(Number(b.dataset.level||0));if(action==='select')this.select();if(action==='help')this.help();if(action==='menu'){S.state.mode='menu';S.input.clear();this.menu();}if(action==='resume')S.pause();if(action==='next')S.start((S.state.level+1)%S.levels.length);});},
 panel(html){$('panel').innerHTML=html;$('overlay').classList.remove('hidden');$('touch').classList.add('hidden');const button=$('panel').querySelector('button');if(button)button.focus({preventScroll:true});},
 menu(){S.loadLevel(0);S.player.reset(S.level.spawn);S.cameraYaw=Math.PI;S.cameraPitch=.48;$('hud').classList.add('hidden');this.panel('<div class="menu-couple" aria-hidden="true">🐼 🐻</div><div class="card-tag">A little garden above the clouds</div><h2>Sky Garden <span>Hop</span></h2><p>Bubu &amp; Dudu’s cozy 3D jumping adventure.<br>Two little buddies. One big heart.</p><button class="primary" data-action="play">Play ♡</button><button class="secondary" data-action="select">Level Select</button><button class="secondary" data-action="help">How to Play</button><br><a href="index.html">← Back to Arcade</a>');},
 select(){this.panel('<h2>Pick a <span>garden</span></h2>'+S.levels.map((l,i)=>{const best=S.best[i];return `<button class="secondary level-button" data-action="play" data-level="${i}">${i+1}. ${l.name}<small> · ${best?'Best '+time(best.time)+' / ♥ '+best.hearts:'A new little adventure'}</small></button>`;}).join('')+'<button class="secondary" data-action="menu">Menu</button>');},
 help(){this.panel('<h2>A little <span>help</span></h2><div class="instructions"><b>Move:</b> WASD / arrows, relative to the camera. Drag to orbit.<br><b>Jump:</b> Space. <b>Swap:</b> Q / Tab. R returns to the flower checkpoint. P / Esc pauses. M mutes.<p><b>🐼 Bubu:</b> press Jump again in mid-air for a double jump. Hold Jump to glide. Crumbling tiles last longer.</p><p><b>🐻 Dudu:</b> push crates into gold plates. Press Down / S + Jump in the air to ground-pound cracked lids or mushrooms.</p><p><b>Touch:</b> left joystick, right Jump / Swap / Pound. Hold Jump to glide. Drag the sky to look around.</p><p>Mint plates work for either buddy and latch open. Gold plates need Dudu or a crate. Falling is always safe: try again at your last flower arch!</p></div><button class="primary" data-action="play">Let’s hop!</button><button class="secondary" data-action="menu">Menu</button>');},
 pause(){this.panel('<div class="card-tag">Take a little breather</div><h2>Garden <span>paused</span></h2><p>Your buddy will wait right here.</p><button class="primary" data-action="resume">Keep hopping ♡</button><button class="secondary" data-action="play" data-level="'+S.state.level+'">Replay</button><button class="secondary" data-action="menu">Menu</button>');},
 summary(){const total=S.level.entities.filter(e=>e.type==='heart').length;this.panel('<div class="card-tag">A lovely little adventure</div><h2>So much <span>love!</span></h2><p>'+S.level.name+' complete</p><div class="rules"><div class="rule"><b>♥ Hearts</b>'+S.state.hearts+' / '+total+'</div><div class="rule"><b>Time</b>'+time(S.state.time)+'</div><div class="rule"><b>Soft retries</b>'+S.state.deaths+'</div><div class="rule"><b>Honey jars</b>'+S.state.honey+'</div></div><button class="primary" data-action="next">'+(S.state.level===2?'Back to Sunny Steps':'Next Level')+' ♡</button><button class="secondary" data-action="play" data-level="'+S.state.level+'">Replay</button><button class="secondary" data-action="menu">Menu</button>');},
 hide(){$('overlay').classList.add('hidden');$('hud').classList.remove('hidden');$('touch').classList.remove('hidden');},
 toast(text,duration=3){$('toast').textContent=text;$('toast').classList.remove('hidden');toastTime=duration;},
 fade(){$('fade').classList.add('active');setTimeout(()=>$('fade').classList.remove('active'),180);},
 sound(){$('mute').textContent=S.audio.muted?'♪̸':'♫';$('mute').setAttribute('aria-pressed',String(S.audio.muted));$('mute').setAttribute('aria-label',S.audio.muted?'Unmute sound':'Mute sound');},
 update(dt){toastTime-=dt;if(toastTime<=0)$('toast').classList.add('hidden');$('character').textContent=S.player.kind==='bubu'?'🐼 Bubu ⇄ Q':'🐻 Dudu ⇄ Q';$('hearts').textContent='♥ '+S.state.hearts;$('level-name').textContent=S.level.name;$('timer').textContent=time(S.state.time);}
 };
})(window.SkyHop);