/* Presentation adapter only: existing engines still own all gameplay state. */
(function(){'use strict';const settings=ArcadeSettings;let engine=null,current=null,help=null,pauseCard=null,helpPaused=false,previousFocus=null;
 // Dash boots at DOMContentLoaded; bind before its first audio sync.
 if(window.Dash)for(const key of ['muted','voices','volume'])settings.bind(Dash.settings,key);
 function audioControls(host){host.innerHTML='<div class="audio-settings" aria-label="Audio settings"><button type="button" data-setting="muted">Sound on</button><button type="button" data-setting="voices">Voices on</button><label>Volume <input aria-label="Volume" data-setting="volume" type="range" min="0" max="1" step="0.05"></label></div>';const mute=host.querySelector('[data-setting="muted"]'),voices=host.querySelector('[data-setting="voices"]'),volume=host.querySelector('input');mute.onclick=()=>settings.set({muted:!settings.state.muted});voices.onclick=()=>settings.set({voices:!settings.state.voices});volume.oninput=()=>settings.set({volume:Number(volume.value)});settings.subscribe(s=>{mute.textContent=s.muted?'Sound off':'Sound on';mute.setAttribute('aria-pressed',String(s.muted));voices.textContent=s.voices?'Voices on':'Voices off';voices.setAttribute('aria-pressed',String(s.voices));volume.value=s.volume;});}
 function mode(){return engine?(engine.race?engine.race.mode:engine.state?engine.state.mode:engine.mode()):'';}
 function pause(){if(engine&&engine.pause)engine.pause();}
 function modal(title,body,button,action){const el=document.createElement('section');el.className='product-modal';el.hidden=true;el.setAttribute('role','dialog');el.setAttribute('aria-modal','true');el.setAttribute('aria-label',title);el.innerHTML='<div class="card"><div class="card-tag">Little Love Arcade</div><h2>'+title+'</h2>'+body+'<button class="primary">'+button+'</button></div>';el.querySelector('button').onclick=action;document.body.append(el);return el;}
 function openHelp(){if(!help)return;previousFocus=document.activeElement;helpPaused=['playing','racing','countdown'].includes(mode());if(helpPaused)pause();help.hidden=false;help.querySelector('button').focus();}
 function closeHelp(){help.hidden=true;try{localStorage.setItem('bubuDuduHelp_'+current.id,'seen');}catch(e){}if(helpPaused&&mode()==='paused')pause();helpPaused=false;if(previousFocus&&previousFocus.isConnected)previousFocus.focus();if(window.ArcadeGame&&!ArcadeGame.started)ArcadeGame.launch();}
 function bindAudio(){if(!engine)return;if(window.Dash){settings.bind(Dash.settings,'muted');settings.bind(Dash.settings,'voices');settings.bind(Dash.settings,'volume');}else if(window.Rescue){settings.bind(Rescue.state,'muted');}else if(engine.audio){settings.bind(engine.audio,'muted');settings.bind(engine.audio,'volume');}
  settings.subscribe(s=>{if(engine.audio&&engine.audio.setVolume)engine.audio.setVolume(s.volume);if(engine.applyAudio)engine.applyAudio(s);if(window.VoiceManager){VoiceManager.setMuted(s.muted);VoiceManager.setVolume(s.volume);}if(window.Dash&&Dash.ui.nodes.mute)Dash.ui.sound();});
 }
 function finish(){const hub=document.getElementById('hub-settings');if(hub){audioControls(hub);return;}
  const file=location.pathname.split('/').pop(),requested=new URLSearchParams(location.search).get('mode');current=ArcadeModes.find(m=>file==='arcade.html'?m.id===requested:m.url===file)||ArcadeModes[0];
  engine=window.ArcadeGame||window.Dash||window.Rescue||window.CozyKart||window.SkyHop;
  document.body.classList.add('product-game');document.body.dataset.productMode=current.id;try{localStorage.setItem('bubuDuduLastMode',current.id);}catch(e){}
  const bar=document.createElement('header');bar.className='product-chrome';bar.innerHTML='<nav class="product-nav" aria-label="Game navigation"><a class="button" href="index.html">← Back to Hub</a><span class="product-name">'+current.name+'</span><button id="product-help" aria-label="How to play '+current.name+'">?</button></nav><div class="product-audio"></div>';document.body.prepend(bar);audioControls(bar.lastElementChild);bindAudio();
  help=modal('How to play', '<p><b>'+current.name+'</b></p><p><b>Keyboard</b><br>'+current.keyboard+'</p><p><b>Touch</b><br>'+current.touch+'</p>','Got it · let’s play',closeHelp);bar.querySelector('button').onclick=openHelp;
  pauseCard=modal('A little breather','<p>Your adventure will wait for you. Ready for another lovely moment?</p>','Continue playing ♡',()=>{pause();syncPause();});const back=document.createElement('a');back.href='index.html';back.className='back';back.textContent='Back to Hub';pauseCard.firstElementChild.append(back);
  function syncPause(){const paused=mode()==='paused',wasHidden=pauseCard.hidden;pauseCard.hidden=!paused||!help.hidden;const overlay=document.getElementById('overlay');if(overlay&&overlay.classList.contains('product-native-paused')!==paused)overlay.classList.toggle('product-native-paused',paused);if(wasHidden&&!pauseCard.hidden)pauseCard.querySelector('button').focus();}
  const overlay=document.getElementById('overlay');if(overlay)new MutationObserver(syncPause).observe(overlay,{attributes:true,childList:true,subtree:true,attributeFilter:['class','hidden']});setInterval(syncPause,120);
  // Shared chrome must not leak shortcut events into any underlying engine.
  document.addEventListener('keydown',function(e){const activeModal=!help.hidden?help:!pauseCard.hidden?pauseCard:null;if(activeModal){if(e.key==='Escape'){e.preventDefault();e.stopImmediatePropagation();if(activeModal===help)closeHelp();else pause();return;}if(e.key==='Tab'){const focusable=activeModal.querySelectorAll('button,a,input'),first=focusable[0],last=focusable[focusable.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}e.stopPropagation();}else if(e.target.closest('.product-chrome'))e.stopPropagation();},true);
  const loading=document.getElementById('product-loading');if(loading)loading.remove();
  if(current.type==='3D'&&(!engine||!engine.renderer)){const error=modal('The garden could not open','<p>This game needs WebGL. Enable hardware acceleration or try another browser.</p>','Back to Hub',()=>{location.href='index.html';});error.hidden=false;return;}
  let seen=false;try{seen=localStorage.getItem('bubuDuduHelp_'+current.id)==='seen';}catch(e){}if(!seen)openHelp();else if(window.ArcadeGame)ArcadeGame.launch();
 }
 // Defer one task: Dash registers its own DOMContentLoaded boot earlier.
 if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>setTimeout(finish,0));else setTimeout(finish,0);
})();