/* The product catalog is the sole source of hub cards, counts and destinations. */
window.ArcadeModes=Object.freeze([
 {id:'catch',name:'Love Catch',description:'Catch their favorites and build a sweet combo.',type:'2D',url:'arcade.html?mode=catch',storageKey:'loveCatchBest',icon:'♡',controls:'Keyboard + Touch',keyboard:'← → or A/D to move · Space to swap · P to pause.',touch:'Drag across the garden or hold the arrows. Tap Swap to change character.'},
 {id:'picnic',name:'Pixel Picnic',description:'Gather six treats, then meet for a picnic.',type:'2D',url:'arcade.html?mode=picnic',storageKey:'loveArcadeBest_picnic',icon:'✿',controls:'Keyboard + Touch',keyboard:'WASD or arrows to explore · Space to swap · P to pause.',touch:'Drag to walk or use the direction buttons. Meet your partner after collecting six treats.'},
 {id:'runner',name:'Together Run',description:'Jump together into an endless garden date.',type:'2D',url:'arcade.html?mode=runner',storageKey:'loveArcadeBest_runner',icon:'➜',controls:'Keyboard + Touch',keyboard:'Space, ↑ or W to jump · P to pause.',touch:'Tap the garden or the Jump button. Jump thorns and collect treats together.'},
 {id:'rescue',name:'Sweet Rescue',description:'Bring little garden friends safely home.',type:'2D',url:'rescue.html',storageKey:'sweetRescueBest',icon:'⌂',controls:'Keyboard + Touch',keyboard:'WASD / arrows to move · Space to swap · Hold E to rescue · R to return · P / Esc to pause.',touch:'Move with the joystick. Hold Rescue near a friend; use Swap and Return for teamwork.'},
 {id:'skyhop',name:'Sky Garden Hop',description:'Hop through a cozy floating garden.',type:'3D',url:'sky-hop.html',storageKey:'skyHopBest',icon:'☁',controls:'Keyboard + Touch',keyboard:'WASD / arrows to move · Space to jump · Q / Tab to swap · Shift to pound · P / Esc to pause.',touch:'Use the joystick, Jump, Swap and Pound. Drag the garden to orbit the camera.'},
 {id:'kart',name:'Cozy Kart',description:'Race your buddies with gifts and sweet drifts.',type:'3D',url:'cozy-kart.html',storageKey:'cozyKartBest',icon:'⚑',controls:'Keyboard + Touch',keyboard:'WASD / arrows to drive · Space + steer to drift · E to use a gift · P / Esc to pause.',touch:'Use steering arrows, Go, Brake and Drift. Tap the gift slot to use your item.'},
 {id:'dash',name:'Lovely Lane Dash',description:'Swap, glide and gather hearts along the lane.',type:'3D',url:'dash.html',storageKey:'lovelyDashBest',icon:'♥',controls:'Keyboard + Touch',keyboard:'A/D or ←/→ for lanes · W/↑/Space to jump · S/↓ to slide · Q/Tab to swap · P/Esc to pause.',touch:'Swipe left/right/up/down or use the buttons. Hold Jump to glide as Bubu; Slide smashes crates as Dudu.'}
]);