(function(K){'use strict';
 const $=id=>document.getElementById(id),keys=new Set(),held=new Map();let use=false,last=0,acc=0,visualTime=0,toastTime=0,ctx=null,master=null;
 K.reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;K.selection={track:0,kind:'bubu',auto:matchMedia('(pointer:coarse)').matches};K.best={};
 try{const saved=JSON.parse(localStorage.getItem('cozyKartBest')||'{}');if(saved&&typeof saved==='object'&&!Array.isArray(saved))K.best=saved;}catch(e){}
 K.audio={muted:false,volume:.3,unlock(){try{if(!ctx){ctx=new(window.AudioContext||window.webkitAudioContext)();master=ctx.createGain();master.connect(ctx.destination);}master.gain.value=this.muted?0:this.volume;if(window.VoiceManager){VoiceManager.setAudioContext(ctx);VoiceManager.setMuted(this.muted);VoiceManager.setVolume(this.volume);VoiceManager.unlock();}if(ctx.state==='suspended')ctx.resume().catch(()=>{});}catch(e){}},tone(name){try{if(!ctx||this.muted)return;if(window.VoiceManager){const event={pickup:'catch',go:'level',lap:'level',finish:'level'}[name];if(event)VoiceManager.playClip(event);}const notes={go:[523,659,1047],pickup:[660,880],boost:[440,660,990],hit:[140,90],finish:[523,659,784,1047],lap:[740,990],tick:[440]};(notes[name]||notes.pickup).forEach((f,i)=>{const t=ctx.currentTime+i*.08,o=ctx.createOscillator(),g=ctx.createGain();o.type='triangle';o.frequency.setValueAtTime(f,t);g.gain.setValueAtTime(.12,t);g.gain.exponentialRampToValueAtTime(.001,t+.2);o.connect(g);g.connect(master);o.start(t);o.stop(t+.21);});}catch(e){}},setVolume(v){this.volume=v;if(window.VoiceManager){VoiceManager.setMuted(this.muted);VoiceManager.setVolume(v);}if(master)master.gain.value=this.muted?0:v;},toggle(){this.muted=!this.muted;this.setVolume(this.volume);$('mute').textContent=this.muted?'♪':'♫';$('mute').setAttribute('aria-pressed',String(this.muted));$('mute').setAttribute('aria-label',this.muted?'Unmute sound':'Mute sound');}};
 K.clearInput=function(){keys.clear();held.clear();use=false;document.querySelectorAll('[data-hold]').forEach(b=>b.classList.remove('held'));};
 K.controls=function(){const has=k=>keys.has(k)||Array.from(held.values()).includes(k);return {steer:(has('arrowright')||has('d')||has('right')?1:0)-(has('arrowleft')||has('a')||has('left')?1:0),throttle:K.selection.auto||has('arrowup')||has('w')||has('throttle'),brake:has('arrowdown')||has('s')||has('brake'),drift:has(' ')||has('drift'),use};};
 const time=t=>{if(!Number.isFinite(t))return '—';return Math.floor(t/60)+':'+(t%60).toFixed(1).padStart(4,'0');};
 function showPanel(html){$('panel').innerHTML=html;$('overlay').classList.remove('hidden');const focus=$('panel').querySelector('button');if(focus)focus.focus({preventScroll:true});}
 function showRace(visible){for(const id of ['hud','race-bottom','minimap','touch'])$(id).classList.toggle('hidden',!visible);}
 K.toast=function(message){$('toast').textContent=message;$('toast').classList.remove('hidden');toastTime=3;};
 K.menu=function(){
  K.clearInput();if(window.VoiceManager)VoiceManager.stop();if(K.race)K.race.mode='menu';showRace(false);$('countdown').classList.add('hidden');$('toast').classList.add('hidden');toastTime=0;
  const best=K.best[K.tracks[K.selection.track].id];
  showPanel('<div class="card-tag">A little race. A lot of love.</div><h1>Bubu &amp; Dudu<br><span>Cozy Kart</span> 🏁</h1><p class="subtitle">Three laps, four buddies, and a basket full of surprises.</p><span class="selection-label">CHOOSE YOUR BUDDY</span><div class="kart-options buddies">'+['bubu','dudu'].map(kind=>'<button data-kind="'+kind+'" aria-pressed="'+(K.selection.kind===kind)+'"><span class="buddy-icon">'+(kind==='bubu'?'🐼':'🐻')+'</span>'+(kind==='bubu'?'Bubu':'Dudu')+'<small>'+(kind==='bubu'?'Pink-heart cruiser':'Honey-gold roadster')+'</small></button>').join('')+'</div><span class="selection-label">PICK A LITTLE ADVENTURE</span><div class="kart-options">'+K.tracks.map((t,i)=>'<button data-track="'+i+'" aria-pressed="'+(i===K.selection.track)+'">'+t.name+'<small>'+t.description+'</small></button>').join('')+'</div><label class="auto-option"><input type="checkbox" id="auto" '+(K.selection.auto?'checked':'')+'> Auto-accelerate · recommended for touch</label><button class="primary" id="start">Let’s race! ♡</button><p class="kart-help">WASD / arrows: drive · Space + steer: drift · E: item<br>Assisted cornering follows the circuit. Steer across the road to dodge honey, grab gifts, and hit mint boost pads.<br>Charge a drift, then release for a boost. P / Esc: pause · M: sound</p><p class="small-note">Track best: '+time(typeof best==='number'?best:NaN)+' · Original fan-made tracks &amp; karts</p><p><a href="index.html">← Back to the arcade</a></p>');
  document.querySelectorAll('[data-kind]').forEach(b=>b.onclick=()=>{K.selection.kind=b.dataset.kind;document.querySelectorAll('[data-kind]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));K.preview();});
  document.querySelectorAll('[data-track]').forEach(b=>b.onclick=()=>{K.selection.track=Number(b.dataset.track);K.menu();K.preview();});
  $('auto').onchange=e=>K.selection.auto=e.target.checked;$('start').onclick=()=>K.start();
 };
 K.preview=function(){const t=K.tracks[K.selection.track];K.buildWorld(t);K.race=K.createRace(t,K.path.length,K.selection.kind);K.race.mode='menu';K.addRaceModels(K.race);K.animateModels(0,0);const f=K.path.at(-7);K.camera.position.copy(f.position).addScaledVector(f.forward,-9);K.camera.position.y+=6;K.camera.lookAt(K.path.at(4).position);};
 K.start=function(){if(window.VoiceManager)VoiceManager.stop();K.clearInput();K.audio.unlock();K.buildWorld(K.tracks[K.selection.track]);K.race=K.createRace(K.tracks[K.selection.track],K.path.length,K.selection.kind);K.addRaceModels(K.race);K.animateModels(0,0);acc=0;$('overlay').classList.add('hidden');showRace(true);$('track-name').textContent=K.race.track.name;$('countdown').textContent='3';$('countdown').classList.remove('hidden');K.toast(K.selection.auto?'Auto-accelerate on · steer, drift, and use gifts!':'Hold W / ↑ to accelerate. Space + steer to drift!');K.followCamera(1,true);updateHUD();};
 K.pause=function(){if(!K.race)return;if(['racing','countdown'].includes(K.race.mode)){K.resumeMode=K.race.mode;K.race.mode='paused';if(window.VoiceManager)VoiceManager.stop();K.clearInput();$('countdown').classList.add('hidden');showPanel('<div class="card-tag">A little pit stop</div><h2>Race <span>paused</span></h2><p>Your buddies are waiting for you.</p><button class="primary" id="resume">Back to the race ♡</button><button class="secondary" id="restart">Restart race</button><button class="secondary" id="choose">Choose track</button><p><a href="index.html">Back to Arcade</a></p>');$('resume').onclick=K.pause;$('restart').onclick=K.start;$('choose').onclick=()=>{K.menu();K.preview();};}else if(K.race.mode==='paused'){K.clearInput();K.race.mode=K.resumeMode;$('overlay').classList.add('hidden');}};
 function summary(){K.clearInput();const r=K.race,p=r.racers[0],key=r.track.id,old=K.best[key];K.best[key]=Math.min(typeof old==='number'&&Number.isFinite(old)?old:Infinity,p.finishTime);try{localStorage.setItem('cozyKartBest',JSON.stringify(K.best));}catch(e){}K.audio.tone('finish');$('countdown').classList.add('hidden');showPanel('<div class="card-tag">'+r.track.name+'</div><h2>'+(['A sweet victory!','Lovely racing!','Made with love!','Every lap is a little adventure!'][r.rank-1])+'</h2><p>Finished '+r.rank+' / 4 in <b>'+time(p.finishTime)+'</b> · Best '+time(K.best[key])+'</p><table class="results"><tbody>'+K.ranking(r).map((buddy,i)=>'<tr class="'+(buddy.player?'player':'')+'"><td>'+(i+1)+'</td><td>'+buddy.name+(buddy.player?' · You':'')+'</td><td>'+(buddy.finishTime!==null?time(buddy.finishTime):'Lap '+buddy.lap+' · racing')+'</td></tr>').join('')+'</tbody></table><button class="primary" id="again">Race again ♡</button><button class="secondary" id="next">Next track →</button><button class="secondary" id="choose">Choose buddy / track</button><p><a href="index.html">← Back to Arcade</a></p>');$('again').onclick=K.start;$('next').onclick=()=>{K.selection.track=(K.selection.track+1)%K.tracks.length;K.start();};$('choose').onclick=()=>{K.menu();K.preview();};}
 function events(){for(const e of K.race.events.splice(0)){if(e.type==='go')K.audio.tone('go');if(e.type==='complete'){summary();continue;}if(!e.racer||!e.racer.player)continue;const messages={pickup:'Gift collected: '+K.itemNames[e.item],use:K.itemNames[e.item]+'!',hit:'Sticky surprise! Keep going ♡',blocked:'Heart shield saved you!',drift:'Sweet drift! Mini boost ♡',lap:e.racer.lap===3?'Final lap! Make it lovely ♡':'Lap '+e.racer.lap+' · Looking lovely!'};if(messages[e.type]){K.toast(messages[e.type]);K.audio.tone(e.type==='hit'?'hit':e.type==='lap'?'lap':e.type==='drift'||e.type==='use'?'boost':'pickup');}}}
 function updateHUD(){const r=K.race,p=r.racers[0];$('position').textContent=r.rank+' / 4';$('lap').textContent=p.lap+' / 3';$('timer').textContent=time(r.time);$('speed').textContent=Math.round(p.speed*3.6);$('drift-fill').style.width=Math.min(100,p.drift/K.CONFIG.driftTime*100)+'%';$('drift-label').textContent=p.boost>0?'Honey-powered boost!':p.drift>=K.CONFIG.driftTime?'Release drift for a boost!':'Hold Space + steer to drift';$('item').innerHTML=p.item?K.itemNames[p.item]+'<small>Use item · E</small>':'♡<small>No item · E</small>';$('item').disabled=!p.item||r.mode!=='racing';$('item').setAttribute('aria-label',p.item?'Use '+K.itemNames[p.item]:'No item held');
  const counting=r.mode==='countdown';$('countdown').classList.toggle('hidden',!counting);if(counting){const text=String(Math.max(1,Math.ceil(r.countdown)));if($('countdown').textContent!==text)K.audio.tone('tick');$('countdown').textContent=text;}
  const map=$('minimap').getContext('2d'),w=180,h=150;map.clearRect(0,0,w,h);const project=p=>({x:w/2+p.x*.85,y:h/2+p.z*.85});map.beginPath();K.path.points.forEach((p,i)=>{const q=project(p);i?map.lineTo(q.x,q.y):map.moveTo(q.x,q.y);});map.closePath();map.strokeStyle='#d0b6bd';map.lineWidth=7;map.stroke();for(const buddy of r.racers){const q=project(K.path.at(buddy.distance,buddy.lane).position);map.beginPath();map.arc(q.x,q.y,buddy.player?5:3.5,0,Math.PI*2);map.fillStyle=buddy.color;map.fill();map.strokeStyle=buddy.player?'#57404a':'white';map.lineWidth=1.5;map.stroke();}
 }
 K.followCamera=function(dt,snap=false){const p=K.race.racers[0],f=K.path.at(p.distance,p.lane),target=K.path.at(p.distance+3,p.lane*.8).position;target.y+=.8;const wanted=f.position.clone().addScaledVector(f.forward,-8.8);wanted.y+=5.5;if(snap)K.camera.position.copy(wanted);else K.camera.position.lerp(wanted,1-Math.exp(-7*dt));K.camera.lookAt(target);};
 function initInput(){
  window.addEventListener('keydown',e=>{if(e.target.matches('input,select,textarea'))return;const key=e.key.toLowerCase();K.audio.unlock();if(K.race&&['racing','countdown'].includes(K.race.mode)&&[' ','arrowup','arrowdown','arrowleft','arrowright'].includes(key))e.preventDefault();keys.add(key);if(e.repeat)return;if(key==='e')use=true;if(key==='p'||key==='escape')K.pause();if(key==='m')K.audio.toggle();});
  window.addEventListener('keyup',e=>keys.delete(e.key.toLowerCase()));window.addEventListener('blur',()=>{K.clearInput();if(K.race&&['racing','countdown'].includes(K.race.mode))K.pause();});document.addEventListener('visibilitychange',()=>{if(document.hidden&&K.race&&['racing','countdown'].includes(K.race.mode))K.pause();});
  window.addEventListener('pointerdown',()=>K.audio.unlock(),{passive:true});
  document.querySelectorAll('[data-hold]').forEach(b=>{b.addEventListener('pointerdown',e=>{e.preventDefault();b.setPointerCapture(e.pointerId);held.set(e.pointerId,b.dataset.hold);b.classList.add('held');});for(const name of ['pointerup','pointercancel','lostpointercapture'])b.addEventListener(name,e=>{held.delete(e.pointerId);if(!Array.from(held.values()).includes(b.dataset.hold))b.classList.remove('held');});});
  $('item').onclick=()=>{use=true;};$('pause').onclick=K.pause;$('mute').onclick=()=>K.audio.toggle();$('volume').oninput=e=>{K.audio.unlock();K.audio.setVolume(Number(e.target.value));};
 }
 function boot(){try{K.renderer=new THREE.WebGLRenderer({canvas:$('world'),antialias:true});K.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.75));K.scene=new THREE.Scene();K.camera=new THREE.PerspectiveCamera(58,1,.1,350);K.scene.add(new THREE.HemisphereLight('#fff8ec','#7b8290',.9));const sun=new THREE.DirectionalLight('#fff3df',.8);sun.position.set(-40,75,20);K.scene.add(sun);const resize=()=>{K.renderer.setSize(innerWidth,innerHeight,false);K.camera.aspect=innerWidth/innerHeight;K.camera.updateProjectionMatrix();};window.addEventListener('resize',resize);resize();initInput();K.preview();K.menu();
   function frame(now){requestAnimationFrame(frame);const dt=Math.min(last?(now-last)/1000:0,.05);last=now;visualTime+=dt;if(['racing','countdown'].includes(K.race.mode)){acc+=dt;while(acc>=K.CONFIG.step){const input=K.controls();K.update(K.race,K.CONFIG.step,input);use=false;acc-=K.CONFIG.step;events();if(K.race.mode==='complete'){acc=0;break;}}}else acc=0;K.animateModels(dt,visualTime);if(K.race.mode!=='menu')K.followCamera(dt);updateHUD();if(toastTime>0){toastTime-=dt;if(toastTime<=0)$('toast').classList.add('hidden');}K.renderer.render(K.scene,K.camera);}requestAnimationFrame(frame);
  }catch(e){console.error(e);showPanel('<h2>The starting line could not open</h2><p>Cozy Kart needs WebGL. Enable hardware acceleration in your browser and try again.</p><a href="index.html">Back to Arcade</a>');}}
 boot();
})(window.CozyKart);